version: '3'

services:
  app:
    build: .
    container_name: ratatouille23_v10
    image: ratatouille23_v10
    ports:
      - "8080:8080"
    environment:
      - ACTIVATION_TOKEN_SECRET=${ENV_ACTIVATION_TOKEN_SECRET}
      - DB_HOST=${ENV_DB_HOST}
      - DB_NAME=${ENV_DB_NAME}
      - DB_PASSWORD=${ENV_DB_PASSWORD}
      - DB_PORT=${ENV_DB_PORT}
      - DB_USERNAME=${ENV_DB_USERNAME}
      - JWT_SECRET=${ENV_JWT_SECRET}
      - SENDGRID_API_KEY=${ENV_SENDGRID_API_KEY}
      - SENDGRID_FROM=${ENV_SENDGRID_FROM}