version: '3.7'
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      DB_NAME: ${ENV_DB_NAME}
      DB_USERNAME: ${ENV_DB_USERNAME}
      DB_PASSWORD: ${ENV_DB_PASSWORD}
      DB_HOST: ${ENV_DB_HOST}
      DB_PORT: ${ENV_DB_PORT}
      ACTIVATION_TOKEN_SECRET: ${ENV_ACTIVATION_TOKEN_SECRET}
      JWT_SECRET: ${ENV_JWT_SECRET}
      SENDGRID_API_KEY: ${ENV_SENDGRID_API_KEY}
      SENDGRID_FROM: ${ENV_SENDGRID_FROM}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  db_data:
