###
POST {{host}}/api/auth/signup
Content-Type: application/json

{
  "name": "mimmo",
  "surname": "maions",
  "email": "domenico.maione@outlook.it",
  "password": "provaprova"
}
###
POST {{host}}/api/auth/signup/op
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzUwNjc3MjYsImV4cCI6MTY3NTE0NDAyNn0.fVXXbxBYs6ffa4nk3XVpeKtAt1Nh6XmUdNtj9csQ7j-1Vm4rW4uZWWwooyHMj54nL8wKG-OqZtMx-sxDY1gphw
Content-Type: application/json

{
  "email": "mimmomaions@gmail.com",
  "name": "ciccio",
  "surname": "merrino",
  "password": "provaprova",
  "role": "SUPERVISOR"
}
###
POST {{host}}/api/auth/signup/op/resetpassword/HH9Silj+ZLcrB1c6jeyWY9TQmmixnz1Q1WrMpOqkUaM
Content-Type: application/json

{
  "password": "ciaomamma"
}
###

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "domenico.maione@outlook.it",
  "password": "provaprova"
}

###
POST {{host}}/api/restaurant
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzUxNzY4MTUsImV4cCI6MTY3NTI1MzExNX0.IOFAmgyIvb58DqnrK1Xly0JNFylVZ4S9f89rYllIFMt8miNoLgY_G37rtIN28LX8ZE36EP2CToJa1W1gmz1OKw
Content-Type: application/json

{
  "id": null,
  "name": "fottuto restaurant",
  "address": "Via marco polo"
}

###
POST {{host}}/api/menu/add
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzUxODAxNDgsImV4cCI6MTY3NTI1NjQ0OH0.l-qQQ1bqCqEHw0_v6LH9ZFQRKb8xdmQgFn0rccso2gba56KoTfJG98pw_FSVONyVUznvpZifppUqYT31RdaCNA


###
GET {{host}}/api/user/{{email}}
###
GET {{host}}/api/auth/validate/user/{{token}}
###
GET {{host}}/api/restaurant/users/HALL_ATTENDANT
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzQ2ODQ2MTUsImV4cCI6MTY3NDc2MDkxNX0.lBeJ0my_blBdpmjdoDk1eFPX5YDvGNJc3VHZWkJAsFhw7CEbidf_Qzt9zGgLB7ZgdPG2kZ4LPO1IVs8lWLNGLw
###
GET {{host}}/api/auth/check/token/{token}
###
DELETE {{host}}/api/menu
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzUxODE0NjIsImV4cCI6MTY3NTI1Nzc2Mn0.DsDOZcLbQ55ZpBr1yLDgWN31qOJTiEiGiw4aGKlvszyOAquHVGhBYl0llelu3pjtreJi1y0ADWEC13W0d2IlXg



###
DELETE {{host}}/api/restaurant
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzUxODI3MDEsImV4cCI6MTY3NTI1OTAwMX0.WLWKp4LyyTWalTwSOvXs8VPMzPp5k7ULv23--x66o0E5lIBIPFsQPKpvIkYWkoN19xpIGK-4ee6O__GOcy2WYg




###