###
POST {{host}}/api/auth/signup
Content-Type: application/json

{
  "name": "franco",
  "surname": "cavaluccio",
  "email": "giacominofedele@gmail.com",
  "password": "Provaprova-1"
}
###
POST {{host}}/api/auth/signup/op
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc3NzU0Njg1LCJleHAiOjE2Nzc4MzA5ODV9.kUyqi-69RmQpCXWFafICLAsXNeaUCozflV6e8f5tODT-O6ei-2Nm4CDz3wap7iq-b8QiBNJ4yIlWvtI9H-RqWA
Content-Type: application/json

{
  "email": "giacomino@gmail.com",
  "name": "marco",
  "surname": "merrino",
  "password": "provaprova",
  "role": "WAITER"
}
###
POST {{host}}/api/auth/signup/op/resetpassword
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoibWltbW9tYWlvbnNAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSVklTT1IiLCJpYXQiOjE2NzUzMzA1MTAsImV4cCI6MTY3NTQwNjgxMH0.SshT-dXwtCucq2-EBY5tcjVAkBx_CYdJ5C19Z_5HUdqubMu4CIsdnS5M3dKiFNOMT4jfvgBwc2RCI7TYCo71ZQ
Content-Type: application/json

{
  "password": "ciaobello"
}
###

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "fagibic549@wireps.com",
  "password": "provaprova"
}

###
POST {{host}}/api/restaurant
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc3MjUyOTkyLCJleHAiOjE2NzczMjkyOTJ9.zY_Lmj3Si_e8BSfWmbpCmxZ6PGDJmYLAdJuRODEwDJdV6jkGMIR6o_f2p3hE9IBrsd9y9AbAVqT_FUSRP2PCEg
Content-Type: application/json

{
  "id": null,
  "name": "quel fottuto ristorante",
  "address": "Via marco polo"
}

###
POST {{host}}/api/menu/add
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc3MjUyOTkyLCJleHAiOjE2NzczMjkyOTJ9.zY_Lmj3Si_e8BSfWmbpCmxZ6PGDJmYLAdJuRODEwDJdV6jkGMIR6o_f2p3hE9IBrsd9y9AbAVqT_FUSRP2PCEg


###
POST {{host}}/api/dish/add
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc3ODY2NjQ1LCJleHAiOjE2Nzc5NDI5NDV9._jHpUVZquZl1yk8kIEekAkkNplH-clhdVj-UM8xzji1YcgOckucjASx2Yt-C8geNoCfbEnFrSeNOJOfmsPdvYw
Content-Type: application/json

{
  "id": null,
  "name": "pizza alla nutella",
  "description": "nutella della ferrero",
  "nameLan": null,
  "descriptionLan": null,
  "cost": 8.50,
  "categoryName": "primo piatto",
  "allergens": [12,14]

}
###
POST {{host}}/api/cart/add/112
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc3NTc2MTM3LCJleHAiOjE2Nzc2NTI0Mzd9.yXkbtN8qWhu_j4fbEZCl5wLsoE2UybhqVCQEcoQOFajUrxSFdoBsxIqijyQCFRWIXGJ6KZNz6xD1ivJgmV88ug
Content-Type: application/json

{
  "dishes": [122]
}
###
POST {{host}}/api/allergens/add
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzcwOTY0MjksImV4cCI6MTY3NzE3MjcyOX0.N6CR5iM9kwmbV875WIoRktlWzfcsYPttaYqRcTBKCGsyEBem1VEGhLm2K1PBcm7SaNXSzce2cuSwzGUW6Eew4g
Content-Type: application/json

{
  "id": null,
  "name": "mandorla"
}
###

POST {{host}}/api/category/add
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc3ODYwMDE4LCJleHAiOjE2Nzc5MzYzMTh9.oKL84JthXP0wuaIUYuwyTsDcDMaHzHJLdVqxTgsUvTyb2bX3r41-4lxIRdkpWC12XM33ifAf4WWUxY3TDFR1vg
Content-Type: application/json

{
  "id": null,
  "name": "primo"
}
###
POST {{host}}/api/category/priority/add/71
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc3NDAzMTAwLCJleHAiOjE2Nzc0Nzk0MDB9.B7iJXWUPhUQNDn-mZmRxNUsZJKMXX85BJz4soRu9EzV-cOYl78chqyaMkPXontzoHU1BwlzoYmJ1ixsnCaDI4Q
Content-Type: application/json

{
  "priority": 3
}
###
POST {{host}}/api/tablerestaurant/add
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc3MjYwODQ4LCJleHAiOjE2NzczMzcxNDh9.mleejajy1dIxI1sQHX5s2uYGypTvgQOKtHXPU59XlGRydtCDzIila2yKoEqki7TsjXpSxaClTvdsdFJgA1XRPQ
Content-Type: application/json

{
  "id": null,
  "seats": 8
}




###
PUT {{host}}/api/dish/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzcxNTY0MzgsImV4cCI6MTY3NzIzMjczOH0.E5DzWdILNNBuLY3w26e1sTXPKcE4Z-ZcDsASq4yjIAtwpmb8bPLYDcCHSBH37SmkYrx4zqGEtw-6HAnpl7Y9tQ
Content-Type: application/json

{
  "id": 50,
  "name": "maccheroni con braciola",
  "description": "pasta fresca e carne di ieri, forse",
  "cost": 15
}
###
PUT {{host}}/api/dish/category
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzcxNjI5MTYsImV4cCI6MTY3NzIzOTIxNn0.WBpzmvOky3z6VbHoHyNDw48ZX7SRg9BzVkVHK5uSmBecxwAuvkymATlYP-Hd8vPrnClFb8g6KOi5rFQYevwpsA
Content-Type: application/json

{
  "id": 50,
  "name": "maccheroni con braciola",
  "description": "pasta fresca e carne di ieri, forse",
  "cost": 15,
  "categoryName": "primo piatto"
}
###
PUT {{host}}/api/cart/close/224
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc4NDM4Njc1LCJleHAiOjE2Nzg1MTQ5NzV9.mVTYgppcFWmUv8H9QQa4VNzBpqsdg5yF9TR9sWz85YxZOdb62nlzHrlE41Bp4v6TXweb55XXIUt4DFExO34Lnw






###
GET {{host}}/api/cartdish/user/107
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc4NDQxMDAyLCJleHAiOjE2Nzg1MTczMDJ9.BwyUUJjKayrLSwU4mnlFCBtlsT-RsalkebfO3aDQnPVzmjU37day-0MqEjNPS3uPjAcxLLwD66cvBSHhU8THwg


###
GET {{host}}/api/cartdish/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc4NDQwNTE2LCJleHAiOjE2Nzg1MTY4MTZ9.jbwYWxRaxbqPnNpaDNBkW2zNtSi_QkMsM-3KrXKal1CTBh52CNcG6-UR4Gjwii4WBlsg5w_3K5yKgXm0BehIwg
###
GET {{host}}/api/cart/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc4NDM5ODk2LCJleHAiOjE2Nzg1MTYxOTZ9.5ChBhnA8350ee4KDWesm1lJ21nVoX-038T4aXIGNx8V7Qw2_48FgiDzHUuGnwQBdxfgfl2PfGNrlGDbeetpL_A

###
GET {{host}}/api/user/all/108
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc3NzU0Njg1LCJleHAiOjE2Nzc4MzA5ODV9.kUyqi-69RmQpCXWFafICLAsXNeaUCozflV6e8f5tODT-O6ei-2Nm4CDz3wap7iq-b8QiBNJ4yIlWvtI9H-RqWA
###
GET {{host}}/api/dish/category/55
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc3ODM2ODYzLCJleHAiOjE2Nzc5MTMxNjN9.QeibV-EW4IDltm98I_kv3eHbUBOKYaT07X3hY1bYLHrGcDz7ZvpmU-iIFPXyKHDssQ0EsXmpF8kogPt6QUKfoA
###
GET {{host}}/api/dishallergens/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc3ODQyOTI5LCJleHAiOjE2Nzc5MTkyMjl9.3ovKMw8bOBp5QySQd-eehgwMPp_X_DA-Q9_txI5Yk1wofu7EjD9pzt6lUZVe4hyMHiFYmLDsclMRCHCaPIoF9A

###
GET {{host}}/api/dish/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc3NjYwMzA0LCJleHAiOjE2Nzc3MzY2MDR9.DUG0RABZDGZEf4aS9h5vH4bPDfhEcDcNaAT6hhj3QzRLGyQYWfHCUV7MbXnwU-zCl-7F2_yIgkt0JNPvPUvbGw

###
GET {{host}}/api/cart/bill/224
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc4NDM4Njc1LCJleHAiOjE2Nzg1MTQ5NzV9.mVTYgppcFWmUv8H9QQa4VNzBpqsdg5yF9TR9sWz85YxZOdb62nlzHrlE41Bp4v6TXweb55XXIUt4DFExO34Lnw

###
GET {{host}}/api/allergens/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzcxNjYwMzIsImV4cCI6MTY3NzI0MjMzMn0.fK13chkJ4mfQHdpyUNe0Z0Te_eTBNYN5S4I1G-1agFvoNVxrPD1jUIF6yFuzembEfO8UTdVe3tunssy9VAbI0g

###
GET {{host}}/api/allergens/11
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzcxNjYwMzIsImV4cCI6MTY3NzI0MjMzMn0.fK13chkJ4mfQHdpyUNe0Z0Te_eTBNYN5S4I1G-1agFvoNVxrPD1jUIF6yFuzembEfO8UTdVe3tunssy9VAbI0g

###
GET {{host}}/api/restaurant/
###
GET {{host}}/api/user/{email}
###
GET {{host}}/api/auth/validate/user/{token}
###
GET {{host}}/api/restaurant/users/HALL_ATTENDANT
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzQ2ODQ2MTUsImV4cCI6MTY3NDc2MDkxNX0.lBeJ0my_blBdpmjdoDk1eFPX5YDvGNJc3VHZWkJAsFhw7CEbidf_Qzt9zGgLB7ZgdPG2kZ4LPO1IVs8lWLNGLw
###
GET {{host}}/api/auth/check/token/{token}
###

GET {{host}}/api/dish/40
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzcxNjUyNDksImV4cCI6MTY3NzI0MTU0OX0.C2I2fyf2UnSGg7PZyIulojCuAuRhDuH1_del10_lFTXUuP0zp_3BecSLXeXaBspmelbHOUaRgO6APeMrUEznsQ

###
GET {{host}}/api/category/58
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzcxNjUyNDksImV4cCI6MTY3NzI0MTU0OX0.C2I2fyf2UnSGg7PZyIulojCuAuRhDuH1_del10_lFTXUuP0zp_3BecSLXeXaBspmelbHOUaRgO6APeMrUEznsQ

###
GET {{host}}/api/category/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzcwOTY5ODgsImV4cCI6MTY3NzE3MzI4OH0.OhccEkZPaKaFezhnwrHrT1YVu4IGJ63KGcSd33oi8ybn6OoitEuV9ZEUqZRuP8jKTV06Hy2h4kdz-tTmZj6EWQ

















###
DELETE {{host}}/api/menu
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzY0MDk1MTEsImV4cCI6MTY3NjQ4NTgxMX0.j7ZywxlE7Os-ny3nRoad_w07DmisGdDAo2w4j_2E7nzkGjjrE-OPPDYKEXN7REVeEglWBv9LjGhZu0Fcu8pfUw

###
DELETE {{host}}/api/restaurant
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzY5ODg0OTMsImV4cCI6MTY3NzA2NDc5M30.6_dWVJBPMjc1GN6elQAD4VUK5oQWA2VxiXQWCXPKtwZwEwfxdUTNa3HZdkVUPJn1jZLLKoORkobsVMan19cR_A

###
DELETE {{host}}/api/category/delete/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzY5MzI5MTcsImV4cCI6MTY3NzAwOTIxN30.mUn7CGC5JbX_lC2sPAEqaO6Ep73VFhQm2pIWo7s-im388I0DxQwn6b7tIDlpHZgOLl9Og1fXPWpyyyBRfMUz0Q

###
DELETE {{host}}/api/dish/50
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzcxNjQ0MjgsImV4cCI6MTY3NzI0MDcyOH0.YS5N-rBPOdOMtjvpKJumqDXw1a8uXPTcm8LGq62Adj9GjADRD76cHjlW-4NMRs7G3bEKAEW8Wpd8DGFWRl_yCw
###
DELETE {{host}}/api/allergens/8
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzcxNjQ0MjgsImV4cCI6MTY3NzI0MDcyOH0.YS5N-rBPOdOMtjvpKJumqDXw1a8uXPTcm8LGq62Adj9GjADRD76cHjlW-4NMRs7G3bEKAEW8Wpd8DGFWRl_yCw
###
DELETE {{host}}/api/user/172
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZmFnaWJpYzU0OUB3aXJlcHMuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjc3ODQzOTQyLCJleHAiOjE2Nzc5MjAyNDJ9.KGOc5zYSgyjetW98uJF9LLbQSyAjpTBOXcvQsnEZ9V_ig25oFu8ddhSBf8Pfv1A5sJkd_2oPYnSjUvDy1T8NtA

###
