###
POST {{host}}/api/auth/signup
Content-Type: application/json

{
  "name": "mimmo",
  "surname": "maions",
  "email": "domenico.maione@outlook.it",
  "password": "provaprova"
}
###
POST {{host}}/api/auth/signup/op
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzUzNTUxNzMsImV4cCI6MTY3NTQzMTQ3M30.oAADTIk9Kf_-laMVgxfmkLVDoirHvjXZWmTOsPei_69OGRoqlK1nrTDEFkgfsvRuP2TgjR6WoFYkHeYWmmaHbQ
Content-Type: application/json

{
  "email": "mimmomaions@gmail.com",
  "name": "ciccio",
  "surname": "merrino",
  "password": "provaprova",
  "role": "SUPERVISOR"
}
###
POST {{host}}/api/auth/signup/op/resetpassword
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoibWltbW9tYWlvbnNAZ21haWwuY29tIiwicm9sZSI6IlNVUEVSVklTT1IiLCJpYXQiOjE2NzUzMzA1MTAsImV4cCI6MTY3NTQwNjgxMH0.SshT-dXwtCucq2-EBY5tcjVAkBx_CYdJ5C19Z_5HUdqubMu4CIsdnS5M3dKiFNOMT4jfvgBwc2RCI7TYCo71ZQ
Content-Type: application/json

{
  "password": "ciaobello"
}
###

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "domenico.maione@outlook.it",
  "password": "provaprova"
}

###
POST {{host}}/api/restaurant
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzUzNTY2MTMsImV4cCI6MTY3NTQzMjkxM30.i-M8_rrHGe0MhTXxyAoBFE34zzAyyZHltla_1I5lF7mYohoqiHzE_fjhkCrpMMwOIFThcGwW2nKk_PdCr8oKQA
Content-Type: application/json

{
  "id": null,
  "name": "fottuto restaurant",
  "address": "Via marco polo"
}

###
POST {{host}}/api/menu/add
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzUzNDgwNjAsImV4cCI6MTY3NTQyNDM2MH0.a1Q40wtwVGuktKPdSK41UCdZ_bYchC5Ka-4e9hZh1fNp29LZ8msi4C3crMulEY1NWImQoNuKYq670km2lzXnsw




###
GET {{host}}/api/user/{email}
###
GET {{host}}/api/auth/validate/user/{token}
###
GET {{host}}/api/restaurant/users/HALL_ATTENDANT
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzQ2ODQ2MTUsImV4cCI6MTY3NDc2MDkxNX0.lBeJ0my_blBdpmjdoDk1eFPX5YDvGNJc3VHZWkJAsFhw7CEbidf_Qzt9zGgLB7ZgdPG2kZ4LPO1IVs8lWLNGLw
###
GET {{host}}/api/auth/check/token/{token}
###
DELETE {{host}}/api/menu
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzUyNDY0NzksImV4cCI6MTY3NTMyMjc3OX0.CtYPqP-RCqIQabi32TfHR778XUKgdLmXpxcTGzgEiCz3sn50XlYOYWz9CkPqKyUGcI9Wl5Tou99BPFREzzqJxA




###
DELETE {{host}}/api/restaurant
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJSYXRhdG91aWxsZTIzLUJhY2tlbmQiLCJzdWIiOiJKV1QgQXV0aCBQcm92aWRlciIsImVtYWlsIjoiZG9tZW5pY28ubWFpb25lQG91dGxvb2suaXQiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2NzUzNTY2MTMsImV4cCI6MTY3NTQzMjkxM30.i-M8_rrHGe0MhTXxyAoBFE34zzAyyZHltla_1I5lF7mYohoqiHzE_fjhkCrpMMwOIFThcGwW2nKk_PdCr8oKQA







###